windows:
  runs-on: windows-2022
  env:
    SCCACHE_ARM64_VERSION: 0.12.0
  strategy:
    fail-fast: false
    matrix:
      arch: [amd64]   # فقط x64
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: actions/setup-go@v5
      with:
        go-version: ^1.22

    - name: Get naiveproxy commit
      id: naive
      shell: bash
      run: echo "commit=$(git -C naiveproxy rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Get Chromium version
      id: chromium
      shell: bash
      run: echo "version=$(cat naiveproxy/CHROMIUM_VERSION)" >> $GITHUB_OUTPUT

    - name: Cache build artifacts
      id: build-cache
      uses: actions/cache@v4
      with:
        path: naiveproxy/src/out
        key: naive-build-${{ steps.naive.outputs.commit }}-${{ hashFiles('cmd/build-naive/cmd_build.go', 'cmd/build-naive/cmd.go') }}-windows-amd64

    - name: Install tools
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: choco install ninja -y

    - name: Install sccache
      if: steps.build-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: choco install sccache -y

    - name: Get sccache version
      if: steps.build-cache.outputs.cache-hit != 'true'
      id: sccache
      shell: pwsh
      run: |
        $rawVersion = sccache --version
        $version = ($rawVersion | Select-Object -First 1) -replace '^sccache\s+', ''
        "version=$version" >> $env:GITHUB_OUTPUT

    - name: Cache sccache files
      if: steps.build-cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ~/AppData/Local/Mozilla/sccache
        key: sccache-windows-amd64-${{ steps.sccache.outputs.version }}-${{ steps.chromium.outputs.version }}
        restore-keys: sccache-windows-amd64-${{ steps.sccache.outputs.version }}-

    - name: Reset sccache stats
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: sccache -z

    - name: Build
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: go run ./cmd/build-naive --target=windows/amd64 build

    - name: Show sccache stats
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: sccache -s

    - name: Package
      run: go run ./cmd/build-naive --target=windows/amd64 package

    - name: Build and run test binary
      shell: bash
      run: |
        cp lib/windows_amd64/libcronet.dll .
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go -C test test -tags with_purego -c -o ../cronet.test.exe .
        ./cronet.test.exe -test.v -test.run=TestEngineVersion

    - uses: actions/upload-artifact@v4
      with:
        name: cronet-windows-amd64
        path: |
          lib/
          include/
          include_cgo.go
